name: my_hive_app
description: A Flutter application using Hive for local data storage.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI
  cupertino_icons: ^1.0.5
  flutter_slidable: ^3.0.1
  
  # Utils
  path_provider: ^2.0.11
  intl: ^0.18.0
  uuid: ^3.0.7
  
  # State Management
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true